// SmartSakay Dagupan — Verified Dagupan City Transport Terminals Seed
const terminalSeedData = [
  {
    name: 'Victory Liner Terminal',
    company: 'Victory Liner, Inc.',
    type: 'bus',
    address: 'Perez Blvd, Dagupan City, Pangasinan',
    lat: 16.0416,
    lng: 120.3402,
    contactNumber: '(075) 522-0925',
    operatingHours: '24/7 (Trips every 30-45 mins)',
    destinations: ['Cubao', 'Pasay', 'Caloocan', 'Baguio City', 'Tuguegarao', 'Santiago, Isabela'],
    amenities: ['Air-conditioned Waiting Lounge', 'Clean Restrooms', 'Ticketing Booth', 'Express Baggage / Cargo', 'CCTV Security'],
    description: 'Premier provincial bus terminal serving northern Luzon and Metro Manila routes with 24/7 departures.',
    isActive: true,
  },
  {
    name: 'Five Star Bus Terminal',
    company: 'Five Star Bus Company',
    type: 'bus',
    address: 'Perez Blvd, Dagupan City, Pangasinan',
    lat: 16.0423,
    lng: 120.3421,
    contactNumber: '(075) 522-2438',
    operatingHours: '3:00 AM - 11:30 PM',
    destinations: ['Cubao', 'Pasay', 'Avenida (Manila)', 'Cabanatuan', 'San Carlos City'],
    amenities: ['Covered Platform', 'Ticketing Booth', 'Restrooms', 'Food Stalls', 'Security Guard'],
    description: 'Major provincial bus terminal with regular and deluxe trips to central Luzon and Metro Manila.',
    isActive: true,
  },
  {
    name: 'Solid North Transit Terminal',
    company: 'Pangasinan Solid North Transit, Inc.',
    type: 'bus',
    address: 'Perez Blvd, Downtown, Dagupan City, Pangasinan',
    lat: 16.0408,
    lng: 120.3395,
    contactNumber: '(075) 515-4422',
    operatingHours: '3:30 AM - 10:00 PM',
    destinations: ['PITX (Parañaque Integrated Terminal)', 'Cubao', 'Kamuning', 'Tarlac City', 'Capas'],
    amenities: ['Point-to-Point Express', 'Restrooms', 'Free Wi-Fi in Terminal', 'Ticketing Counter'],
    description: 'Serves daily express and regular routes to PITX and Metro Manila via TPLEX expressway.',
    isActive: true,
  },
  {
    name: 'Genesis Transport / JoyBus Executive Terminal',
    company: 'Genesis Transport Service, Inc.',
    type: 'bus',
    address: 'M.H. Del Pilar St. cor. Perez Blvd, Dagupan City, Pangasinan',
    lat: 16.0441,
    lng: 120.3381,
    contactNumber: '(075) 529-8733',
    operatingHours: '4:00 AM - 9:00 PM',
    destinations: ['Cubao', 'Avenida', 'Baguio City', 'Clark Airport Shuttle', 'Baler, Aurora'],
    amenities: ['JoyBus Luxury Lounge', 'Executive Reclining Waiting Seats', 'Wi-Fi', 'Complimentary Water', 'Clean Restrooms'],
    description: 'Executive non-stop luxury bus service to Baguio, Metro Manila, and Clark International Airport.',
    isActive: true,
  },
  {
    name: 'Dagupan Bus Co. Terminal',
    company: 'Dagupan Bus Co., Inc.',
    type: 'bus',
    address: 'Perez Blvd, Dagupan City, Pangasinan',
    lat: 16.0435,
    lng: 120.3415,
    contactNumber: '(075) 522-1234',
    operatingHours: '4:30 AM - 8:30 PM',
    destinations: ['Cubao', 'Baguio City', 'San Fernando, La Union', 'Alaminos / Hundred Islands'],
    amenities: ['Standard Waiting Area', 'Ticketing Office', 'Restrooms'],
    description: 'Historic bus company providing regional Pangasinan and inter-provincial passenger connections.',
    isActive: true,
  },
  {
    name: 'CSI City Mall Lucao Multimodal Terminal Hub',
    company: 'Dagupan City Transport Federation',
    type: 'multimodal',
    address: 'CSI The City Mall Grounds, Lucao District, Dagupan City',
    lat: 16.0278,
    lng: 120.3218,
    contactNumber: '(075) 523-8888',
    operatingHours: '5:00 AM - 9:30 PM',
    destinations: ['Downtown Dagupan', 'Binmaley', 'Lingayen', 'Calasiao', 'San Fabian'],
    amenities: ['Mall Parking Integration', 'Covered Terminal Bays', 'Security Staff', 'Direct Mall Access', 'Well-lit Loading Zones'],
    description: 'Premier western Dagupan transport terminal connecting city jeepneys, provincial shuttles, and tricycle feeder lines.',
    isActive: true,
  },
  {
    name: 'Downtown Dagupan Central Jeepney Staging Hub',
    company: 'City Government of Dagupan / POSO',
    type: 'jeepney',
    address: 'Perez Blvd & A.B. Fernandez Ave, Downtown Dagupan City',
    lat: 16.0433,
    lng: 120.3342,
    contactNumber: 'POSO Hotline (075) 522-2000',
    operatingHours: '5:00 AM - 10:00 PM',
    destinations: ['Lucao / CSI', 'Bonuan Boquig', 'Bonuan Binloc', 'San Fabian', 'Mangaldan', 'Calasiao', 'Tambac'],
    amenities: ['POSO Traffic Assistance Post', 'Street Level Boarding Sheds', 'Directional Signages'],
    description: 'Central downtown staging point where all urban and inter-municipality jeepneys meet and transfer passengers.',
    isActive: true,
  },
  {
    name: 'Perez TODA Central Tricycle Terminal',
    company: 'Perez Blvd Tricycle Operators and Drivers Association',
    type: 'tricycle',
    address: 'Near Old PNR Station, Perez Blvd, Dagupan City',
    lat: 16.0425,
    lng: 120.3375,
    contactNumber: 'City TFRB (075) 522-8321',
    operatingHours: '5:30 AM - 10:30 PM',
    destinations: ['Perez Commercial Zone', 'Malimgas Market', 'Galvan St', 'Herrero-Perez Residential Areas'],
    amenities: ['Official Fare Matrix Display Board', 'TODA Dispatch Booth', 'Regulated Queue Line'],
    description: 'Regulated tricycle terminal operating under Dagupan City Ordinance fare rates with certified dispatchers.',
    isActive: true,
  },
];

module.exports = terminalSeedData;
